const {test, expect} = require('@playwright/test')

test('Login + security', async ({page}) => {
    await page.goto('https://pin-up.ua/')
    await page.waitForTimeout(1000)
    await page.locator('[data-testid="loginBtn"]').click()
    await page.locator('[data-testid="loginFormAuthInput"]').fill('paw_patrol@zabarna.net') 
    await page.waitForTimeout(1000)
    await page.locator('[data-testid="loginFormPasswordInput"]').fill('paw_patrol') 
    await page.waitForTimeout(1000)
    await page.locator('[data-testid="loginBtn"]').click()
    await page.waitForTimeout(1000)
    await page.locator('[data-testid="profileBtn"]').click()
    await page.waitForTimeout(1000)
    await expect(page).toHaveURL('https://pin-up.ua/profile')
    await page.waitForTimeout(1000)
    await page.locator('[data-testid="profileSecurityHistorySessionsLink"]').click()
    await page.waitForTimeout(1000)
    await expect(page).toHaveURL('https://pin-up.ua/profile/security')
    await page.waitForTimeout(1000)
})